### ISSUE TITLE
Incompatible with recent versions of Buildbot

### ISSUE THREAD

**Issue by pmatos** [russell/bb-pytest#4]
With `buildbot 0.9.6` you get when importing steps:
```
File "/home/pmatos/.pyenv/versions/3.6.0/envs/buildbot3-venv/lib/python3.6/site-packages/bb_pytest/step.py", line 19, in <module>
            from buildbot.status import testresult
        builtins.ImportError: cannot import name 'testresult'
```

**Comment by fleimgruber** [comment]
See https://github.com/russell/bb-pytest/pull/3.

**Comment by russell** [comment]
PR was merged and a new release was pushed to pypi

**Comment by russell** [comment]
Thanks for reporting this :)

Sorry it took so long to act.  I'm going to close this, feel free to open another bug if you hit any issues
